# This is a basic workflow to help you get started with Actions

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '8.0.332+9'
        distribution: 'temurin'
        cache: maven
    - name: Build (without tests)
      run: mvn package -DskipTests
    - name: Unit tests
      run: mvn integration-test
    - name: Mutation tests
      run: mvn -Ppitest integration-test
